version: "3.5"
services:
  php_fpm:
      build: .
      container_name: laravel_php_fpm
      working_dir: /usr/share/nginx/laravel
      networks:
        - laravel
      volumes:
          - ./:/usr/share/nginx/laravel
  nginx:
      image: nginx:1.15
      container_name: laravel_nginx
      working_dir: /usr/share/nginx/laravel
      networks:
        - laravel
      ports:
          - "8080:80"
      volumes:
          - ./:/usr/share/nginx/laravel
          - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
      image: mysql:8
      container_name: laravel_mysql
      networks:
        - laravel
      environment:
        - MYSQL_DATABASE=laravel
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=laravel
        - MYSQL_PASSWORD=password
networks:
  laravel:
    driver: bridge